relativeURLs = true
googleAnalytics = "UA-159072578-1"
title = "Haining Du"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]

[author]
name = "Haining Du"

[params]
title = "PhD Candidate,"
institution = "Michigan State University"
logo = "stefanie-stantcheva-2-compressed-square.jpg"
Twitter = "hainingdu"
Email = "duhainin@msu.edu"
